#!/usr/bin/env bash
#
# The portable revocation proof: a self-contained CRL-checking verifier, plus the
# fixture pair it judges. `up` mints and starts, `down` removes everything.
#
#   ./scripts/local-crl-verifier.sh up      # mint + start (idempotent)
#   ./scripts/local-crl-verifier.sh down    # stop + remove containers and network
#   ./scripts/local-crl-verifier.sh status
#
# WHY THIS EXISTS RATHER THAN A COMMITTED REVOKED CERT.
# S5 proves revocation against UAT, and it can only run where a specific revoked
# UAT identity happens to sit on disk — `certs/` is gitignored, so that fixture
# never travels. The two obvious repairs were both wrong: committing the key
# material is wrong even for a cert whose only capability is to be refused, and
# raising an account to platform_super_admin so the simulator can call the revoke
# route is a security change bought for convenience.
#
# The scenario's claim is not "UAT revokes". It is "a revoked certificate is
# refused". That is provable anywhere, by anyone, with an authority of our own.
#
# WHY IT BRINGS ITS OWN BROKER instead of using the dev stack. Measured
# 2026-08-13/14 on this machine:
#
#   - `enable_crl_check` is ABSENT from the running dev broker's config, i.e. off.
#   - Turning it on for `ssl:default` would fail closed on EVERY existing dev
#     leaf, because they all carry `crlDistributionPoints = http://localhost:8080/
#     pki/station-ca.crl` and `localhost` inside the broker container is the
#     broker. The artifact is fine; the URL baked into the leaves points at
#     nothing.
#   - That listener also had 19 live connections at the time of measuring. It is
#     shared. Flipping a fail-closed flag on it to obtain a test fixture would
#     take everyone else's work down with it.
#
# So this brings up its own broker on its own network and its own port, and
# touches `csms-emqx` not at all.
#
# WHY THE CRL IS SERVED FROM A CONTAINER AND NOT FROM THE HOST. EMQX fetches the
# CRL over HTTP from the URI in the presented leaf. Serving it from a host port
# and pointing the CRLDP at the bridge gateway FAILS here: the host firewall
# drops bridge-to-host, measured as `http=000` from inside the container while
# `localhost:8899` answered 200 on the host. Both ends therefore live on a
# user-defined docker network, where the CRLDP is a container name that always
# resolves.
#
# THE PAIR IS THE PROOF. Both leaves are signed by the same throwaway CA in the
# same run, with the same key type and the same extension profile, and both are
# valid for ten years. The ONLY difference is that one serial was passed to
# `openssl ca -revoke` before the CRL was generated. So "refused" versus
# "connected" has exactly one candidate cause. Nothing is committed: every byte
# here is regenerated by `up`, which is also why the private keys are harmless.
#
set -euo pipefail

CMD="${1:-up}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/certs/local-crl"
NET=sim-crl-net
CRL_HOST=sim-crl-host          # also the CRLDP hostname baked into every leaf
VERIFIER=sim-crl-verifier
HOST_PORT="${SIM_CRL_PORT:-8885}"
EMQX_IMAGE="${SIM_CRL_EMQX_IMAGE:-emqx/emqx:5.8.6}"
NGINX_IMAGE="${SIM_CRL_NGINX_IMAGE:-nginx:1.25-alpine}"

REVOKED_ID=stn_r0000001
VALID_ID=stn_r0000002

down() {
  docker rm -f "$VERIFIER" "$CRL_HOST" >/dev/null 2>&1 || true
  docker network rm "$NET" >/dev/null 2>&1 || true
  echo "local-crl-verifier: down (containers + network removed; $OUT_DIR left in place)"
}

status() {
  printf 'network   %s\n' "$(docker network inspect "$NET" >/dev/null 2>&1 && echo present || echo absent)"
  for c in "$CRL_HOST" "$VERIFIER"; do
    printf '%-9s %s\n' "$c" "$(docker inspect -f '{{.State.Status}}' "$c" 2>/dev/null || echo absent)"
  done
  printf 'fixtures  %s\n' "$([ -r "$OUT_DIR/$REVOKED_ID.pem" ] && echo present || echo absent)"
}

case "$CMD" in
  down)   down; exit 0 ;;
  status) status; exit 0 ;;
  up)     ;;
  *) echo "usage: $0 [up|down|status]" >&2; exit 2 ;;
esac

for img in "$EMQX_IMAGE" "$NGINX_IMAGE"; do
  if ! docker image inspect "$img" >/dev/null 2>&1; then
    echo "local-crl-verifier: image $img is not present locally." >&2
    echo "  Pull it, or override via SIM_CRL_EMQX_IMAGE / SIM_CRL_NGINX_IMAGE." >&2
    exit 1
  fi
done

down >/dev/null 2>&1 || true
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/crlroot" "$OUT_DIR/db"
: > "$OUT_DIR/db/index.txt"
echo 3000 > "$OUT_DIR/db/serial"
echo 1000 > "$OUT_DIR/db/crlnumber"

# --- our own authority ------------------------------------------------------
openssl ecparam -name prime256v1 -genkey -noout -out "$OUT_DIR/ca-key.pem"
openssl req -x509 -new -key "$OUT_DIR/ca-key.pem" -sha256 -days 3650 \
  -subj "/CN=Sim Local Revocation CA" \
  -addext "basicConstraints=critical,CA:TRUE" \
  -addext "keyUsage=critical,keyCertSign,cRLSign" \
  -out "$OUT_DIR/ca.pem"

cat > "$OUT_DIR/ca.cnf" <<EOF
[ca]
default_ca = CA_default
[CA_default]
dir = $OUT_DIR
database = $OUT_DIR/db/index.txt
serial = $OUT_DIR/db/serial
crlnumber = $OUT_DIR/db/crlnumber
new_certs_dir = $OUT_DIR/db
certificate = $OUT_DIR/ca.pem
private_key = $OUT_DIR/ca-key.pem
default_md = sha256
default_crl_days = 3650
policy = pol
email_in_dn = no
unique_subject = no
copy_extensions = none
[pol]
commonName = supplied
[srv]
basicConstraints = CA:FALSE
keyUsage = digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost,IP:127.0.0.1
[leaf]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
crlDistributionPoints = URI:http://$CRL_HOST/station-ca.crl
EOF

mint() { # <cn> <ext-section>
  openssl ecparam -name prime256v1 -genkey -noout -out "$OUT_DIR/$1-key.pem"
  chmod 600 "$OUT_DIR/$1-key.pem"
  openssl req -new -key "$OUT_DIR/$1-key.pem" -subj "/CN=$1" -out "$OUT_DIR/$1.csr"
  openssl ca -batch -config "$OUT_DIR/ca.cnf" -extensions "$2" -days 3650 \
    -in "$OUT_DIR/$1.csr" -out "$OUT_DIR/$1.raw" 2>/dev/null
  openssl x509 -in "$OUT_DIR/$1.raw" -out "$OUT_DIR/$1.pem"   # strip the text dump
  cp "$OUT_DIR/ca.pem" "$OUT_DIR/$1-chain.pem"
}

mint server srv
mint "$REVOKED_ID" leaf
mint "$VALID_ID" leaf

# --- the revocation, at mint time -------------------------------------------
openssl ca -config "$OUT_DIR/ca.cnf" -revoke "$OUT_DIR/$REVOKED_ID.pem" >/dev/null 2>&1
openssl ca -config "$OUT_DIR/ca.cnf" -gencrl -out "$OUT_DIR/crl.pem" 2>/dev/null
openssl crl -in "$OUT_DIR/crl.pem" -outform DER -out "$OUT_DIR/crlroot/station-ca.crl"
chmod -R a+rX "$OUT_DIR"
chmod 600 "$OUT_DIR"/*-key.pem

# --- the verifier -----------------------------------------------------------
docker network create "$NET" >/dev/null
docker run -d --name "$CRL_HOST" --network "$NET" \
  -v "$OUT_DIR/crlroot:/usr/share/nginx/html:ro" "$NGINX_IMAGE" >/dev/null
docker run -d --name "$VERIFIER" --network "$NET" -p "$HOST_PORT:8883" \
  -v "$OUT_DIR:/certs:ro" \
  -e EMQX_ALLOW_ANONYMOUS=true \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CACERTFILE=/certs/ca.pem \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/certs/server.pem \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/certs/server-key.pem \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__VERIFY=verify_peer \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__FAIL_IF_NO_PEER_CERT=true \
  -e EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__ENABLE_CRL_CHECK=true \
  "$EMQX_IMAGE" >/dev/null

printf 'local-crl-verifier: waiting for the listener'
for _ in $(seq 1 45); do
  if docker exec "$VERIFIER" emqx ctl listeners 2>/dev/null | grep -q 'ssl:default'; then
    echo; break
  fi
  printf '.'; sleep 2
done

# Fail loudly if the verifier cannot fetch the list — a broker that cannot read
# the CRL under a fail-closed posture refuses EVERYTHING, which would make the
# revoked leaf look refused for the right reason by accident.
code="$(docker exec "$VERIFIER" curl -s -o /dev/null -w '%{http_code}' -m 5 \
  "http://$CRL_HOST/station-ca.crl" 2>/dev/null || echo 000)"
if [ "$code" != "200" ]; then
  echo "local-crl-verifier: the verifier cannot fetch the CRL (http=$code)." >&2
  echo "  Under the fail-closed posture it would refuse every certificate, so the" >&2
  echo "  proof would pass for the wrong reason. Refusing to report success." >&2
  exit 1
fi

echo "local-crl-verifier: up on mqtts://localhost:$HOST_PORT  (CRL http=200)"
echo "  revoked : $OUT_DIR/$REVOKED_ID.pem  serial $(openssl x509 -in "$OUT_DIR/$REVOKED_ID.pem" -noout -serial | cut -d= -f2)  ON the CRL"
echo "  control : $OUT_DIR/$VALID_ID.pem  serial $(openssl x509 -in "$OUT_DIR/$VALID_ID.pem" -noout -serial | cut -d= -f2)  not on the CRL"
echo
echo "Run the pair (both, or neither proves anything):"
echo "  npm run build"
echo "  node dist/cli/index.js run --scenario scenarios/tls-floor/s7-rejects-revoked-cert-local.yaml  --target local-crl"
echo "  node dist/cli/index.js run --scenario scenarios/tls-floor/s7b-accepts-nonrevoked-cert-local.yaml --target local-crl"
echo "  ./scripts/local-crl-verifier.sh down"
